live_config_reload = true

[shell]
program = "/run/current-system/sw/bin/fish"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 15

[cursor]
thickness = 0.2
vi_mode_style = { shape = "Block", blinking = "Never" }

[selection]
# Automatically copy selections
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "xdg-open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
# Detect OSC 8 escape sequence hyperlinks
hyperlinks = true
# Additional hint detection rules (?)
post_processing = true
# Remain in "hint mode" after selecting one
persist = false
# Enable hint interaction with the mouse, conditionally with mods
mouse = { enabled = true, mods = "Shift" }
# Keybinding for entering "hint mode"
binding = { key = "e", mods = "Control|Shift" }

[colors.cursor]
text = "#0e0e0e"
cursor = "#eeeeee"

[colors.primary]
background = "#0e0e0e"
foreground = "#eeeeee"

[colors.normal]
blue = "#00bbff"
cyan = "#23ccdd"
green = "#0cb890"
magenta = "#bb89ff"
red = "#ea3377"
white = "#777777"
yellow = "#ffcc66"

[colors.bright]
black = "#333333"
blue = "#aaddff"
cyan = "#61d6d6"
green = "#61e294"
magenta = "#eeaaff"
red = "#fb5599"
white = "#eeeeee"
yellow = "#ff8876"
